apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clark
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:SHreyank4Real/for-argocd.git
    targetRevision: main
    path: loggenerator
    helm:
      valueFiles:
        - values/clark.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: clark

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true