apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  # ← this one
spec:
  project: default
  source:
    repoURL: git@github.com:SHreyank4Real/for-argocd.git
    targetRevision: main
    path: minio
    helm:
      valueFiles:
        - dev-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true