{{- if and .Values.aws .Values.aws.accessKey .Values.aws.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "aws-credentials" .Values.aws.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretKey | b64enc | quote }}
{{- end }}
